### PR TITLE
uptime support for Tizen

### PR DESCRIPTION
**Pull request by JRazek**
Hello, I am a [`flutter-tizen`](https://github.com/flutter-tizen/) project maintainer and I added support for the platform for which we are developing.

### CODE REVIEW

**Review by Crimsons — APPROVED** [review]
lgtm

**Review by Crimsons — COMMENTED** [review]
Hey, would it make sense to mention the Tizen support in README.MD as well?

**Comment by JRazek** [comment]
> Hey, would it make sense to mention the Tizen support in README.MD as well?

@Crimsons there's no need. Current state will be fine :)

**Comment by JRazek** [comment]
Hi, @Crimsons. Should I add something to this PR?

**Comment by Crimsons** [comment]
> Hi, @Crimsons. Should I add something to this PR?

hey, fine by me.

**Comment by JRazek** [comment]
> > Hi, @Crimsons. Should I add something to this PR?
> 
> hey, fine by me.

Would you mind merging it then :)?

**Pull request merged**
